// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IError<T> = { err: T, };

export type IResult<T> = { result: T, };

export type IResultList<T> = { results: Array<T>, };

export type IResultPass = { pass: boolean, };
