use std::path::Path;

use dto_bindgen_backend_ts::{
    TypeScriptDeclaration, TypeScriptModule, TypeScriptParameter, TypeScriptProperty,
    TypeScriptType, TypeScriptValue,
};

use crate::package_matrix::WasmPackageSpec;

const WASM_DECLARATION_HEADER: &str =
    "// @generated by cargo xtask generate wasm via dto_bindgen\n// Do not edit by hand.\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WasmDeclarationFile {
    pub relative_path: String,
    pub contents: String,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct WasmDeclarationInventory {
    public_functions: &'static [WasmPublicFunction],
    support_exports: &'static [WasmSupportExport],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct WasmPublicFunction {
    name: &'static str,
    parameter: Option<&'static str>,
    return_kind: WasmReturnKind,
    low_level: LowLevelSignature,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum WasmReturnKind {
    String,
    Any,
    Void,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LowLevelSignature {
    parameters: usize,
    returns: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct WasmSupportExport {
    name: &'static str,
    export_type: WasmSupportExportType,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum WasmSupportExportType {
    Memory,
    Table,
    Function(LowLevelSignature),
    NumberFunction(usize),
}

macro_rules! public_function {
    ($name:literal, $parameter:expr, $return_kind:ident, $low_parameters:literal, $low_returns:literal) => {
        WasmPublicFunction {
            name: $name,
            parameter: $parameter,
            return_kind: WasmReturnKind::$return_kind,
            low_level: LowLevelSignature {
                parameters: $low_parameters,
                returns: $low_returns,
            },
        }
    };
}

macro_rules! memory_export {
    () => {
        WasmSupportExport {
            name: "memory",
            export_type: WasmSupportExportType::Memory,
        }
    };
}

macro_rules! table_export {
    ($name:literal) => {
        WasmSupportExport {
            name: $name,
            export_type: WasmSupportExportType::Table,
        }
    };
}

macro_rules! void_function_export {
    ($name:literal, $parameters:literal) => {
        WasmSupportExport {
            name: $name,
            export_type: WasmSupportExportType::Function(LowLevelSignature {
                parameters: $parameters,
                returns: 0,
            }),
        }
    };
}

macro_rules! number_function_export {
    ($name:literal, $parameters:literal) => {
        WasmSupportExport {
            name: $name,
            export_type: WasmSupportExportType::NumberFunction($parameters),
        }
    };
}

pub fn write_declaration_files(root: &Path, spec: WasmPackageSpec) -> Result<(), String> {
    let package_dir = root.join(spec.package_dir);
    for file in declaration_files(spec)? {
        crate::fs::write_if_changed(&package_dir.join(&file.relative_path), &file.contents)?;
    }
    Ok(())
}

pub fn declaration_files(spec: WasmPackageSpec) -> Result<Vec<WasmDeclarationFile>, String> {
    let inventory = inventory(spec)?;
    Ok(vec![
        WasmDeclarationFile {
            relative_path: format!("dist/{}.d.ts", spec.out_name),
            contents: render_declaration_module(primary_module(spec, inventory)),
        },
        WasmDeclarationFile {
            relative_path: format!("dist/{}_bg.wasm.d.ts", spec.out_name),
            contents: render_declaration_module(sidecar_module(spec, inventory)),
        },
    ])
}

fn inventory(spec: WasmPackageSpec) -> Result<WasmDeclarationInventory, String> {
    match spec.key {
        "event_codec" => Ok(WasmDeclarationInventory {
            public_functions: EVENT_CODEC_FUNCTIONS,
            support_exports: EVENT_CODEC_SUPPORT_EXPORTS,
        }),
        "replica_store" => Ok(WasmDeclarationInventory {
            public_functions: REPLICA_STORE_FUNCTIONS,
            support_exports: SQL_WASM_SUPPORT_EXPORTS,
        }),
        "replica_sync" => Ok(WasmDeclarationInventory {
            public_functions: REPLICA_SYNC_FUNCTIONS,
            support_exports: SQL_WASM_SUPPORT_EXPORTS,
        }),
        _ => Err(format!(
            "missing wasm declaration inventory for {}",
            spec.key
        )),
    }
}

fn primary_module(spec: WasmPackageSpec, inventory: WasmDeclarationInventory) -> TypeScriptModule {
    let mut module = TypeScriptModule::new(format!("dist/{}.d.ts", spec.out_name));
    for function in inventory.public_functions {
        module.push_declaration(TypeScriptDeclaration::function(
            function.name,
            public_parameters(function.parameter),
            public_return_type(function.return_kind),
        ));
    }
    module.push_declaration(TypeScriptDeclaration::type_alias(
        "InitInput",
        init_input_type(),
    ));
    module.push_declaration(TypeScriptDeclaration::type_alias(
        "InitOutput",
        init_output_type(inventory),
    ));
    module.push_declaration(TypeScriptDeclaration::type_alias(
        "SyncInitInput",
        sync_init_input_type(),
    ));
    module.push_declaration(TypeScriptDeclaration::function(
        "initSync",
        vec![TypeScriptParameter::new(
            "module",
            TypeScriptType::union(vec![
                TypeScriptType::object(vec![TypeScriptProperty::new(
                    "module",
                    TypeScriptType::named("SyncInitInput"),
                )]),
                TypeScriptType::named("SyncInitInput"),
            ]),
        )],
        TypeScriptType::named("InitOutput"),
    ));
    module.push_declaration(TypeScriptDeclaration::default_function(
        "__wbg_init",
        vec![
            TypeScriptParameter::new(
                "module_or_path",
                TypeScriptType::union(vec![
                    TypeScriptType::object(vec![TypeScriptProperty::new(
                        "module_or_path",
                        TypeScriptType::union(vec![
                            TypeScriptType::named("InitInput"),
                            promise_of(TypeScriptType::named("InitInput")),
                        ]),
                    )]),
                    TypeScriptType::named("InitInput"),
                    promise_of(TypeScriptType::named("InitInput")),
                ]),
            )
            .optional(),
        ],
        promise_of(TypeScriptType::named("InitOutput")),
    ));
    module
}

fn sidecar_module(spec: WasmPackageSpec, inventory: WasmDeclarationInventory) -> TypeScriptModule {
    let mut module = TypeScriptModule::new(format!("dist/{}_bg.wasm.d.ts", spec.out_name));
    for export in inventory.support_exports {
        if matches!(export.export_type, WasmSupportExportType::Memory) {
            module.push_declaration(support_export_declaration(*export));
        }
    }
    for function in inventory.public_functions {
        module.push_declaration(TypeScriptDeclaration::constant(
            function.name,
            Some(low_level_function_type(function.low_level)),
            TypeScriptValue::string(""),
        ));
    }
    for export in inventory.support_exports {
        if !matches!(export.export_type, WasmSupportExportType::Memory) {
            module.push_declaration(support_export_declaration(*export));
        }
    }
    module
}

fn render_declaration_module(module: TypeScriptModule) -> String {
    let mut rendered = String::from(WASM_DECLARATION_HEADER);
    rendered.push_str(&module.render_declaration());
    rendered
}

fn public_parameters(parameter: Option<&'static str>) -> Vec<TypeScriptParameter> {
    parameter
        .map(|name| vec![TypeScriptParameter::new(name, TypeScriptType::String)])
        .unwrap_or_default()
}

fn public_return_type(kind: WasmReturnKind) -> TypeScriptType {
    match kind {
        WasmReturnKind::String => TypeScriptType::String,
        WasmReturnKind::Any => TypeScriptType::Any,
        WasmReturnKind::Void => TypeScriptType::Void,
    }
}

fn init_input_type() -> TypeScriptType {
    TypeScriptType::union(vec![
        TypeScriptType::named("RequestInfo"),
        TypeScriptType::named("URL"),
        TypeScriptType::named("Response"),
        TypeScriptType::named("BufferSource"),
        TypeScriptType::named("WebAssembly.Module"),
    ])
}

fn sync_init_input_type() -> TypeScriptType {
    TypeScriptType::union(vec![
        TypeScriptType::named("BufferSource"),
        TypeScriptType::named("WebAssembly.Module"),
    ])
}

fn init_output_type(inventory: WasmDeclarationInventory) -> TypeScriptType {
    let mut properties = vec![TypeScriptProperty::new("memory", memory_type()).readonly()];
    properties.extend(inventory.public_functions.iter().map(|function| {
        TypeScriptProperty::new(function.name, low_level_function_type(function.low_level))
            .readonly()
    }));
    properties.extend(
        inventory
            .support_exports
            .iter()
            .filter(|export| !matches!(export.export_type, WasmSupportExportType::Memory))
            .map(|export| {
                TypeScriptProperty::new(export.name, support_export_type(*export)).readonly()
            }),
    );
    TypeScriptType::object(properties)
}

fn support_export_declaration(export: WasmSupportExport) -> TypeScriptDeclaration {
    TypeScriptDeclaration::constant(
        export.name,
        Some(support_export_type(export)),
        TypeScriptValue::string(""),
    )
}

fn support_export_type(export: WasmSupportExport) -> TypeScriptType {
    match export.export_type {
        WasmSupportExportType::Memory => memory_type(),
        WasmSupportExportType::Table => TypeScriptType::named("WebAssembly.Table"),
        WasmSupportExportType::Function(signature) => low_level_function_type(signature),
        WasmSupportExportType::NumberFunction(parameters) => {
            low_level_number_function_type(parameters)
        }
    }
}

fn memory_type() -> TypeScriptType {
    TypeScriptType::named("WebAssembly.Memory")
}

fn low_level_number_function_type(parameters: usize) -> TypeScriptType {
    TypeScriptType::function(number_parameters(parameters), TypeScriptType::Number)
}

fn low_level_function_type(signature: LowLevelSignature) -> TypeScriptType {
    TypeScriptType::function(
        number_parameters(signature.parameters),
        low_level_return_type(signature.returns),
    )
}

fn number_parameters(count: usize) -> Vec<TypeScriptParameter> {
    (0..count)
        .map(|index| {
            TypeScriptParameter::new(low_level_parameter_name(index), TypeScriptType::Number)
        })
        .collect()
}

fn low_level_parameter_name(index: usize) -> String {
    match index {
        0 => "a".to_owned(),
        1 => "b".to_owned(),
        2 => "c".to_owned(),
        3 => "d".to_owned(),
        _ => format!("arg{index}"),
    }
}

fn low_level_return_type(count: usize) -> TypeScriptType {
    match count {
        0 => TypeScriptType::Void,
        1 => TypeScriptType::Number,
        _ => TypeScriptType::tuple(vec![TypeScriptType::Number; count]),
    }
}

fn promise_of(type_expr: TypeScriptType) -> TypeScriptType {
    TypeScriptType::generic("Promise", vec![type_expr])
}

const EVENT_CODEC_FUNCTIONS: &[WasmPublicFunction] = &[
    public_function!("article_tags", Some("article_json"), String, 2, 4),
    public_function!("coop_tags", Some("coop_json"), String, 2, 4),
    public_function!("document_tags", Some("document_json"), String, 2, 4),
    public_function!("farm_crdt_change_tags", Some("input_json"), String, 2, 4),
    public_function!("farm_file_metadata_tags", Some("file_json"), String, 2, 4),
    public_function!("farm_tags", Some("farm_json"), String, 2, 4),
    public_function!(
        "farm_workspace_manifest_tags",
        Some("workspace_json"),
        String,
        2,
        4
    ),
    public_function!("file_metadata_tags", Some("metadata_json"), String, 2, 4),
    public_function!("follow_tags", Some("follow_json"), String, 2, 4),
    public_function!("generic_repost_tags", Some("repost_json"), String, 2, 4),
    public_function!("gift_wrap_tags", Some("gift_wrap_json"), String, 2, 4),
    public_function!("group_admins_tags", Some("group_json"), String, 2, 4),
    public_function!("group_create_group_tags", Some("group_json"), String, 2, 4),
    public_function!("group_create_invite_tags", Some("group_json"), String, 2, 4),
    public_function!("group_delete_event_tags", Some("group_json"), String, 2, 4),
    public_function!("group_delete_group_tags", Some("group_json"), String, 2, 4),
    public_function!("group_edit_metadata_tags", Some("group_json"), String, 2, 4),
    public_function!("group_join_request_tags", Some("group_json"), String, 2, 4),
    public_function!("group_leave_request_tags", Some("group_json"), String, 2, 4),
    public_function!("group_members_tags", Some("group_json"), String, 2, 4),
    public_function!("group_metadata_tags", Some("group_json"), String, 2, 4),
    public_function!("group_put_user_tags", Some("group_json"), String, 2, 4),
    public_function!("group_remove_user_tags", Some("group_json"), String, 2, 4),
    public_function!("group_roles_tags", Some("group_json"), String, 2, 4),
    public_function!("http_auth_tags", Some("auth_json"), String, 2, 4),
    public_function!("job_feedback_tags", Some("job_json"), String, 2, 4),
    public_function!("job_request_tags", Some("job_json"), String, 2, 4),
    public_function!("job_result_tags", Some("job_json"), String, 2, 4),
    public_function!("knowledge_claim_tags", Some("claim_json"), String, 2, 4),
    public_function!(
        "knowledge_field_report_tags",
        Some("report_json"),
        String,
        2,
        4
    ),
    public_function!(
        "knowledge_relation_tags",
        Some("relation_json"),
        String,
        2,
        4
    ),
    public_function!("knowledge_review_tags", Some("review_json"), String, 2, 4),
    public_function!("knowledge_source_tags", Some("source_json"), String, 2, 4),
    public_function!("list_set_tags", Some("list_json"), String, 2, 4),
    public_function!("list_tags", Some("list_json"), String, 2, 4),
    public_function!(
        "operational_listing_tags",
        Some("listing_json"),
        String,
        2,
        4
    ),
    public_function!(
        "operational_listing_tags_full",
        Some("listing_json"),
        String,
        2,
        4
    ),
    public_function!("message_file_tags", Some("message_json"), String, 2, 4),
    public_function!("message_tags", Some("message_json"), String, 2, 4),
    public_function!("plot_tags", Some("plot_json"), String, 2, 4),
    public_function!("reaction_tags", Some("reaction_json"), String, 2, 4),
    public_function!("relay_auth_tags", Some("auth_json"), String, 2, 4),
    public_function!("report_tags", Some("report_json"), String, 2, 4),
    public_function!("repost_tags", Some("repost_json"), String, 2, 4),
    public_function!("seal_tags", Some("seal_json"), String, 2, 4),
    public_function!(
        "social_ask_build_authored_draft",
        Some("input_json"),
        String,
        2,
        4
    ),
    public_function!(
        "social_comment_build_authored_draft",
        Some("input_json"),
        String,
        2,
        4
    ),
    public_function!(
        "social_photo_update_build_authored_draft",
        Some("input_json"),
        String,
        2,
        4
    ),
    public_function!(
        "social_update_build_authored_draft",
        Some("input_json"),
        String,
        2,
        4
    ),
    public_function!("wiki_article_tags", Some("article_json"), String, 2, 4),
    public_function!(
        "wiki_merge_request_tags",
        Some("request_json"),
        String,
        2,
        4
    ),
    public_function!("wiki_redirect_tags", Some("redirect_json"), String, 2, 4),
    public_function!(
        "verify_and_decode_event_json",
        Some("event_json"),
        String,
        2,
        4
    ),
    public_function!("contract_manifest_json", None, String, 0, 4),
];

const EVENT_CODEC_SUPPORT_EXPORTS: &[WasmSupportExport] = &[
    memory_export!(),
    table_export!("__wbindgen_externrefs"),
    number_function_export!("__wbindgen_malloc", 2),
    number_function_export!("__wbindgen_realloc", 4),
    void_function_export!("__externref_table_dealloc", 1),
    void_function_export!("__wbindgen_free", 3),
    void_function_export!("__wbindgen_start", 0),
];

const REPLICA_STORE_FUNCTIONS: &[WasmPublicFunction] = &[
    public_function!("replica_store_export_begin", None, Any, 0, 3),
    public_function!("replica_store_export_finish", None, Void, 0, 2),
    public_function!("replica_store_export_json", None, Any, 0, 3),
    public_function!("replica_store_farm_create", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_farm_delete", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_farm_find_many", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_farm_find_one", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_farm_update", Some("opts_json"), Any, 2, 3),
    public_function!(
        "replica_store_farm_gcs_location_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_gcs_location_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_gcs_location_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_gcs_location_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_gcs_location_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_claim_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_claim_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_claim_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_claim_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_claim_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_member_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_tag_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_tag_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_tag_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_tag_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_farm_tag_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_gcs_location_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_gcs_location_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_gcs_location_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_gcs_location_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_gcs_location_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!("replica_store_import_json", Some("dump_json"), Void, 2, 2),
    public_function!(
        "replica_store_log_error_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_log_error_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_log_error_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_log_error_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_log_error_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_media_image_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_media_image_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_media_image_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_media_image_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_media_image_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_event_head_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_event_head_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_event_head_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_event_head_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_event_head_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_relay_set",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_relay_unset",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_profile_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_relay_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_relay_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_relay_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_relay_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_nostr_relay_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!("replica_store_plot_create", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_plot_delete", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_plot_find_many", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_plot_find_one", Some("opts_json"), Any, 2, 3),
    public_function!("replica_store_plot_update", Some("opts_json"), Any, 2, 3),
    public_function!(
        "replica_store_plot_gcs_location_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_gcs_location_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_gcs_location_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_gcs_location_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_gcs_location_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_tag_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_tag_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_tag_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_tag_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_plot_tag_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!("replica_store_reset_database", None, Void, 0, 2),
    public_function!("replica_store_run_migrations", None, Void, 0, 2),
    public_function!(
        "replica_store_trade_product_create",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_delete",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_find_many",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_find_one",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_location_set",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_location_unset",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_media_set",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_media_unset",
        Some("opts_json"),
        Any,
        2,
        3
    ),
    public_function!(
        "replica_store_trade_product_update",
        Some("opts_json"),
        Any,
        2,
        3
    ),
];

const REPLICA_SYNC_FUNCTIONS: &[WasmPublicFunction] = &[
    public_function!("replica_sync_ingest_event", Some("event_json"), Any, 2, 3),
    public_function!("replica_sync_sync_all", Some("request_json"), Any, 2, 3),
];

const SQL_WASM_SUPPORT_EXPORTS: &[WasmSupportExport] = &[
    memory_export!(),
    number_function_export!("__wbindgen_malloc", 2),
    number_function_export!("__wbindgen_realloc", 4),
    void_function_export!("__wbindgen_exn_store", 1),
    number_function_export!("__externref_table_alloc", 0),
    table_export!("__wbindgen_externrefs"),
    void_function_export!("__externref_table_dealloc", 1),
    void_function_export!("__wbindgen_start", 0),
];

#[cfg(test)]
mod tests {
    use crate::package_matrix::wasm_package_specs;

    use super::{WASM_DECLARATION_HEADER, declaration_files};

    #[test]
    fn declaration_files_are_dto_owned_and_cover_primary_and_sidecar_paths() {
        for spec in wasm_package_specs() {
            let files = declaration_files(*spec).expect("declaration files");
            assert_eq!(files.len(), 2);
            assert!(
                files
                    .iter()
                    .any(|file| file.relative_path == format!("dist/{}.d.ts", spec.out_name))
            );
            assert!(
                files.iter().any(
                    |file| file.relative_path == format!("dist/{}_bg.wasm.d.ts", spec.out_name)
                )
            );
            for file in files {
                assert!(file.contents.starts_with(WASM_DECLARATION_HEADER));
                assert!(!file.contents.contains("tslint:disable"));
                assert!(!file.contents.contains("eslint-disable"));
            }
        }
    }

    #[test]
    fn generated_declarations_include_public_wasm_entrypoints() {
        let specs = wasm_package_specs();
        let events = declaration_files(specs[0]).expect("event declarations");
        assert!(
            events[0]
                .contents
                .contains("export function operational_listing_tags")
        );
        assert!(
            events[1]
                .contents
                .contains("export declare const operational_listing_tags")
        );
        for authored in [
            "social_ask_build_authored_draft",
            "social_comment_build_authored_draft",
            "social_photo_update_build_authored_draft",
            "social_update_build_authored_draft",
        ] {
            assert!(
                events[0]
                    .contents
                    .contains(&format!("export function {authored}"))
            );
            assert!(
                events[1]
                    .contents
                    .contains(&format!("export declare const {authored}"))
            );
        }
        for retired in [
            "calendar_date_event_tags",
            "calendar_event_rsvp_tags",
            "calendar_tags",
            "calendar_time_event_tags",
        ] {
            assert!(!events[0].contents.contains(retired));
            assert!(!events[1].contents.contains(retired));
        }
        for retired in ["comment_tags", "post_tags"] {
            assert!(
                !events[0]
                    .contents
                    .contains(&format!("export function {retired}("))
            );
            assert!(
                !events[1]
                    .contents
                    .contains(&format!("export declare const {retired}:"))
            );
        }

        let replica_store = declaration_files(specs[1]).expect("replica store declarations");
        assert!(
            replica_store[0]
                .contents
                .contains("export function replica_store_farm_create")
        );
        assert!(
            replica_store[0]
                .contents
                .contains("export function replica_store_farm_update")
        );
        assert!(
            replica_store[0]
                .contents
                .contains("export function replica_store_plot_update")
        );
        assert!(
            replica_store[1]
                .contents
                .contains("export declare const replica_store_farm_create")
        );
        assert!(
            replica_store[1]
                .contents
                .contains("export declare const replica_store_farm_update")
        );
        assert!(
            replica_store[1]
                .contents
                .contains("export declare const replica_store_plot_update")
        );

        let replica_sync = declaration_files(specs[2]).expect("replica sync declarations");
        assert!(
            replica_sync[0]
                .contents
                .contains("export function replica_sync_sync_all")
        );
        assert!(
            replica_sync[1]
                .contents
                .contains("export declare const replica_sync_sync_all")
        );
    }
}
