use crate::{
    manifest::manifest_file_name,
    manifest::package_manifest,
    package_matrix::{PackageSpec, package_specs},
    ts::{
        generated_constants_file, generated_header, generated_types_file,
        strip_legacy_generated_header,
    },
};

pub struct PackageOutput {
    pub spec: PackageSpec,
    pub types_ts: Option<&'static str>,
    pub constants_ts: Option<&'static str>,
}

pub struct GeneratedFile {
    pub relative_path: String,
    pub contents: String,
}

impl PackageOutput {
    pub fn files(&self) -> Vec<GeneratedFile> {
        let mut files = Vec::new();
        if let Some(types_ts) = self.types_ts {
            files.push(GeneratedFile {
                relative_path: format!("src/generated/{}", generated_types_file()),
                contents: render_ts(types_ts),
            });
        }
        if let Some(constants_ts) = self.constants_ts {
            files.push(GeneratedFile {
                relative_path: format!("src/generated/{}", generated_constants_file()),
                contents: render_ts(constants_ts),
            });
        }
        files.push(GeneratedFile {
            relative_path: format!("src/generated/{}", manifest_file_name()),
            contents: render_manifest(self.spec),
        });
        files.push(GeneratedFile {
            relative_path: "src/index.ts".to_owned(),
            contents: render_index(self),
        });
        files
    }
}

pub fn package_outputs() -> Vec<PackageOutput> {
    vec![
        PackageOutput {
            spec: spec_by_key("core"),
            types_ts: Some(radroots_core_bindings::TYPES_TS),
            constants_ts: None,
        },
        PackageOutput {
            spec: spec_by_key("events_indexed"),
            types_ts: Some(radroots_events_indexed_bindings::TYPES_TS),
            constants_ts: None,
        },
        PackageOutput {
            spec: spec_by_key("identity"),
            types_ts: None,
            constants_ts: Some(radroots_identity_bindings::CONSTANTS_TS),
        },
        PackageOutput {
            spec: spec_by_key("types"),
            types_ts: Some(radroots_types_bindings::TYPES_TS),
            constants_ts: None,
        },
    ]
}

fn spec_by_key(key: &str) -> PackageSpec {
    package_specs()
        .iter()
        .copied()
        .find(|spec| spec.key == key)
        .unwrap_or_else(|| panic!("missing package spec for {key}"))
}

fn render_ts(source: &str) -> String {
    let body = strip_legacy_generated_header(source);
    format!("{}{}", generated_header(), body.trim_start())
}

fn render_manifest(spec: PackageSpec) -> String {
    let mut value = package_manifest(spec);
    value["generated"] = serde_json::Value::Bool(true);
    format!(
        "{}\n",
        serde_json::to_string_pretty(&value).expect("manifest json serializes")
    )
}

fn render_index(output: &PackageOutput) -> String {
    let mut lines = Vec::new();
    if output.types_ts.is_some() {
        lines.push("export * from \"./generated/types.js\";");
    }
    if output.constants_ts.is_some() {
        lines.push("export * from \"./generated/constants.js\";");
    }
    if lines.is_empty() {
        lines.push("export {};");
    }
    format!("{}\n", lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::{package_outputs, render_ts};

    #[test]
    fn renders_sdk_header() {
        let output = render_ts("// legacy\n\nexport type A = string;\n");
        assert!(output.starts_with("// @generated by cargo xtask generate ts"));
        assert!(output.contains("export type A = string;"));
    }

    #[test]
    fn includes_core_and_types_outputs() {
        let package_names = package_outputs()
            .into_iter()
            .map(|output| output.spec.package_name)
            .collect::<Vec<_>>();
        assert!(package_names.contains(&"@radroots/core-bindings"));
        assert!(package_names.contains(&"@radroots/events-indexed-bindings"));
        assert!(package_names.contains(&"@radroots/identity-bindings"));
        assert!(package_names.contains(&"@radroots/types-bindings"));
    }
}
