pub fn generated_header() -> &'static str {
    "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
}

pub fn generated_types_file() -> &'static str {
    "types.ts"
}

pub fn generated_constants_file() -> &'static str {
    "constants.ts"
}

pub fn normalize_lf(value: &str) -> String {
    value.replace("\r\n", "\n")
}

#[cfg(test)]
mod tests {
    use super::{generated_constants_file, generated_header, generated_types_file, normalize_lf};

    #[test]
    fn generated_header_matches_contract() {
        assert_eq!(
            generated_header(),
            "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
        );
    }

    #[test]
    fn generated_file_names_are_stable() {
        assert_eq!(generated_types_file(), "types.ts");
        assert_eq!(generated_constants_file(), "constants.ts");
    }

    #[test]
    fn normalizes_line_endings() {
        assert_eq!(normalize_lf("a\r\nb\n"), "a\nb\n");
    }
}
