pub fn generated_header() -> &'static str {
    "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
}

pub fn generated_types_file() -> &'static str {
    "types.ts"
}

pub fn generated_constants_file() -> &'static str {
    "constants.ts"
}

pub fn normalize_lf(value: &str) -> String {
    value.replace("\r\n", "\n")
}

pub fn strip_legacy_generated_header(value: &str) -> String {
    let normalized = normalize_lf(value);
    normalized
        .strip_prefix("// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n\n")
        .unwrap_or(&normalized)
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::{
        generated_constants_file, generated_header, generated_types_file, normalize_lf,
        strip_legacy_generated_header,
    };

    #[test]
    fn generated_header_matches_contract() {
        assert_eq!(
            generated_header(),
            "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
        );
    }

    #[test]
    fn generated_file_names_are_stable() {
        assert_eq!(generated_types_file(), "types.ts");
        assert_eq!(generated_constants_file(), "constants.ts");
    }

    #[test]
    fn normalizes_line_endings() {
        assert_eq!(normalize_lf("a\r\nb\n"), "a\nb\n");
    }

    #[test]
    fn strips_legacy_ts_rs_header() {
        let source = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n\nexport type A = string;\n";
        assert_eq!(
            strip_legacy_generated_header(source),
            "export type A = string;\n"
        );
    }
}
