pub fn generated_header() -> &'static str {
    "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
}

pub fn generated_types_file() -> &'static str {
    "types.ts"
}

pub fn generated_constants_file() -> &'static str {
    "constants.ts"
}

pub fn generated_kinds_file() -> &'static str {
    "kinds.ts"
}

#[cfg(test)]
mod tests {
    use super::{
        generated_constants_file, generated_header, generated_kinds_file, generated_types_file,
    };

    #[test]
    fn generated_header_matches_contract() {
        assert_eq!(
            generated_header(),
            "// @generated by cargo xtask generate ts\n// Do not edit by hand.\n"
        );
    }

    #[test]
    fn generated_file_names_are_stable() {
        assert_eq!(generated_types_file(), "types.ts");
        assert_eq!(generated_constants_file(), "constants.ts");
        assert_eq!(generated_kinds_file(), "kinds.ts");
    }
}
