[package]
name = "radroots_core_bindings"
description = "Generated bindings for Radroots core primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
dto_bindgen = { workspace = true }
dto_bindgen_core = { workspace = true }
radroots_core = { workspace = true, features = ["serde", "std"] }
