use radroots_sdk_binding_model::{self as ts, TsValue};

pub fn constants_module() -> ts::TsModule {
    ts::module(vec![
        ts::import_type(&["RadrootsListingProductTagKeys"], "./types.js"),
        ts::const_decl(
            "RADROOTS_LISTING_PRODUCT_TAG_KEYS",
            Some(ts::reference("RadrootsListingProductTagKeys")),
            TsValue::Array(vec![
                TsValue::String("key".to_owned()),
                TsValue::String("title".to_owned()),
                TsValue::String("category".to_owned()),
                TsValue::String("summary".to_owned()),
                TsValue::String("process".to_owned()),
                TsValue::String("lot".to_owned()),
                TsValue::String("location".to_owned()),
                TsValue::String("profile".to_owned()),
                TsValue::String("year".to_owned()),
            ]),
        ),
    ])
}

pub fn kinds_module() -> ts::TsModule {
    ts::module(vec![
        ts::const_number("KIND_PROFILE", 0),
        ts::const_number("KIND_POST", 1),
        ts::const_number("KIND_FOLLOW", 3),
        ts::const_number("KIND_REACTION", 7),
        ts::const_number("KIND_SEAL", 13),
        ts::const_number("KIND_MESSAGE", 14),
        ts::const_number("KIND_MESSAGE_FILE", 15),
        ts::const_number("KIND_GIFT_WRAP", 1059),
        ts::const_number("KIND_COMMENT", 1111),
        ts::const_number("KIND_GEOCHAT", 20000),
        ts::const_number("KIND_LIST_MUTE", 10000),
        ts::const_number("KIND_LIST_PINNED_NOTES", 10001),
        ts::const_number("KIND_LIST_READ_WRITE_RELAYS", 10002),
        ts::const_number("KIND_LIST_BOOKMARKS", 10003),
        ts::const_number("KIND_LIST_COMMUNITIES", 10004),
        ts::const_number("KIND_LIST_PUBLIC_CHATS", 10005),
        ts::const_number("KIND_LIST_BLOCKED_RELAYS", 10006),
        ts::const_number("KIND_LIST_SEARCH_RELAYS", 10007),
        ts::const_number("KIND_LIST_SIMPLE_GROUPS", 10009),
        ts::const_number("KIND_LIST_RELAY_FEEDS", 10012),
        ts::const_number("KIND_LIST_INTERESTS", 10015),
        ts::const_number("KIND_LIST_MEDIA_FOLLOWS", 10020),
        ts::const_number("KIND_LIST_EMOJIS", 10030),
        ts::const_number("KIND_LIST_DM_RELAYS", 10050),
        ts::const_number("KIND_LIST_GOOD_WIKI_AUTHORS", 10101),
        ts::const_number("KIND_LIST_GOOD_WIKI_RELAYS", 10102),
        ts::const_number("KIND_LIST_SET_FOLLOW", 30000),
        ts::const_number("KIND_LIST_SET_GENERIC", 30001),
        ts::const_number("KIND_LIST_SET_RELAY", 30002),
        ts::const_number("KIND_LIST_SET_BOOKMARK", 30003),
        ts::const_number("KIND_LIST_SET_CURATION", 30004),
        ts::const_number("KIND_LIST_SET_VIDEO", 30005),
        ts::const_number("KIND_LIST_SET_PICTURE", 30006),
        ts::const_number("KIND_LIST_SET_KIND_MUTE", 30007),
        ts::const_number("KIND_LIST_SET_INTEREST", 30015),
        ts::const_number("KIND_LIST_SET_EMOJI", 30030),
        ts::const_number("KIND_LIST_SET_RELEASE_ARTIFACT", 30063),
        ts::const_number("KIND_LIST_SET_APP_CURATION", 30267),
        ts::const_number("KIND_LIST_SET_CALENDAR", 31924),
        ts::const_number("KIND_LIST_SET_STARTER_PACK", 39089),
        ts::const_number("KIND_LIST_SET_MEDIA_STARTER_PACK", 39092),
        ts::const_number("KIND_FARM", 30340),
        ts::const_number("KIND_PLOT", 30350),
        ts::const_number("KIND_COOP", 30360),
        ts::const_number("KIND_DOCUMENT", 30361),
        ts::const_number("KIND_RESOURCE_AREA", 30370),
        ts::const_number("KIND_RESOURCE_HARVEST_CAP", 30371),
        ts::const_number("KIND_ACCOUNT_CLAIM", 30380),
        ts::const_number("KIND_APP_DATA", 30078),
        ts::const_number("KIND_LISTING", 30402),
        ts::const_number("KIND_APPLICATION_HANDLER", 31990),
        ts::const_number("KIND_TRADE_LISTING_VALIDATE_REQ", 5321),
        ts::const_number("KIND_TRADE_LISTING_VALIDATE_RES", 6321),
        ts::const_number("KIND_WORKER_TRADE_TRANSITION_PROOF_REQ", 5322),
        ts::const_number("KIND_WORKER_TRADE_TRANSITION_PROOF_RES", 6322),
        ts::const_number("KIND_TRADE_ORDER_REQUEST", 3422),
        ts::const_number("KIND_TRADE_ORDER_RESPONSE", 3423),
        ts::const_number("KIND_TRADE_ORDER_DECISION", 3423),
        ts::const_number("KIND_TRADE_ORDER_REVISION", 3424),
        ts::const_number("KIND_TRADE_ORDER_REVISION_RESPONSE", 3425),
        ts::const_number("KIND_TRADE_QUESTION", 3426),
        ts::const_number("KIND_TRADE_ANSWER", 3427),
        ts::const_number("KIND_TRADE_DISCOUNT_REQUEST", 3428),
        ts::const_number("KIND_TRADE_DISCOUNT_OFFER", 3429),
        ts::const_number("KIND_TRADE_DISCOUNT_ACCEPT", 3430),
        ts::const_number("KIND_TRADE_FORBIDDEN_3431", 3431),
        ts::const_number("KIND_TRADE_CANCEL", 3432),
        ts::const_number("KIND_TRADE_FULFILLMENT_UPDATE", 3433),
        ts::const_number("KIND_TRADE_RECEIPT", 3434),
        ts::const_number("KIND_TRADE_VALIDATION_RECEIPT", 3440),
        ts::const_number("KIND_TRADE_LISTING_ORDER_REQ", 3422),
        ts::const_number("KIND_TRADE_LISTING_ORDER_RES", 3423),
        ts::const_number("KIND_TRADE_LISTING_ORDER_REVISION_REQ", 3424),
        ts::const_number("KIND_TRADE_LISTING_ORDER_REVISION_RES", 3425),
        ts::const_number("KIND_TRADE_LISTING_QUESTION_REQ", 3426),
        ts::const_number("KIND_TRADE_LISTING_ANSWER_RES", 3427),
        ts::const_number("KIND_TRADE_LISTING_DISCOUNT_REQ", 3428),
        ts::const_number("KIND_TRADE_LISTING_DISCOUNT_OFFER_RES", 3429),
        ts::const_number("KIND_TRADE_LISTING_DISCOUNT_ACCEPT_REQ", 3430),
        ts::const_number("KIND_TRADE_LISTING_CANCEL_REQ", 3432),
        ts::const_number("KIND_TRADE_LISTING_FULFILLMENT_UPDATE_REQ", 3433),
        ts::const_number("KIND_TRADE_LISTING_RECEIPT_REQ", 3434),
        ts::const_number("KIND_JOB_REQUEST_MIN", 5000),
        ts::const_number("KIND_JOB_REQUEST_MAX", 5999),
        ts::const_number("KIND_JOB_RESULT_MIN", 6000),
        ts::const_number("KIND_JOB_RESULT_MAX", 6999),
        ts::const_number("KIND_JOB_FEEDBACK", 7000),
    ])
}
